// query {
//     authors{
//       id
//       name
//       photo
//       bio
//       posts{
//         id
//         title
//         slug
//         featuredPost
//         featuredImage
//         categories{
//           name
//           slug
//           id
//         }
//         comments{
//           comment
//           name
//           email
//         }
//       }
//       __typename
//     }
//   }

// query {
//     categories{
//       id
//        name
//        slug
//        id
//       posts{
//         id
//         title
//         slug
//         featuredPost
//         featuredImage
//         author{
//           id
//           name
//           bio
//           photo
//         }
//         comments{
//           comment
//           name
//           email
//         }
//       }
//     }
//   }

// query {
//     posts{
//         id
//         title
//         slug
//         featuredPost
//         featuredImage
//       author{
//         id
//         name
//         bio
//         photo
//       }
//         categories{
//           name
//           slug
//           id
//         }
//         comments{
//           comment
//           name
//           email
//         }
//       }
//   }
